runtime: java
env: flex
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
  PROXY_ENABLED: false
  APP_PORT: 8080
  FETCH_ONLINE: false
  ROOT_DIR: ../datasets/
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1