server:
  port: ${APP_PORT:80}
  compression:
    enabled: true
    min-response-size: 5120
    mime-types: application/json,application/xml,text/xml,text/plain
spring:
  jackson:
    default-property-inclusion: non_null
resource:
  fetch-online: ${FETCH_ONLINE:false}
  parent-uri: ${PARENT_URI:https://raw.githubusercontent.com/rahulakkina/LoksabhaElectionCaseStudy-2019/master/datasets/}
  root-dir: ${ROOT_DIR}
  news-uri: ${NEWS_URI:https://news.google.com/rss/search}
http:
  use-proxy: ${PROXY_ENABLED:false}
  proxy:
    host: ${PROXY_HOST:gcloud-proxy.google.com}
    port: ${PROXY_PORT:80}
poll:
  job:
    schedule: ${SCHEDULE_INTERVAL:900000}